### ISSUE TITLE
Mouse 3 & 4 not registering 

### ISSUE THREAD

**Issue by ghost** [shiiion/Ishiiruka#8]
Been getting into PrimeHack and optimizing my control scheme, but it seems like mouse 3 & 4 (side/thumb buttons) aren't being recognized as being clicked. The control configurator is registering them, but the game isn't at all. I have mouse 3 registered to - and mouse 4 registered to +, and I'm using a Razer Basilisk V2.

**Comment by SirMangler** [comment]
In MP1 and MP2 we disabled the beam and visor menus so those buttons will not work except from in the Map menu. In Prime 3 you can still access Hypermode but not the visor menu.

We have made this change because the reticle is locked, making it impossible for you to select anything in the menus. See the beams/visor buttons.

https://github.com/shiiion/dolphin/wiki/Installation#beams-and-visors

Are they working in the Map/Menu screens?

**Comment by ghost** [comment]
Yeah, they're working. Sorry, I didn't consider that.
