### ISSUE TITLE
Failure on startup: Metroid Prime Trilogy

### ISSUE THREAD

**Issue by Jounreay** [shiiion/Ishiiruka#9]
Hello, I recently downloaded version 5.0 of Dolphin, and found this repo in a search for more intuitive controls. When attempting to start the metroid prime trilogy, emulation immediately crashes. It is not an issue with the file -- I was playing it just fine through the official dolphin release. I have tried numerous configuration settings in both graphics and application, but to no avail. 

I noticed there was a recent commit 5 hours ago, and I am worried something may have been affected. Are there any logging configs in place so I may troubleshoot? I noticed there were not any logs printed to the usual place for dolphin.

Any response would be appreciated.

Thank you

**Comment by SirMangler** [comment]
This is somewhat common when coming from other versions. Try change your video backend to D3D11 or anything not OpenGL. Dolphin is buggy.

If you downloaded 5.0, as in the **stable** release. That release is way older. Ishiiruka is also quite modified. It's more than possible your settings/shader cache has been corrupted.  

You may wish to purge your Config folder, your Cache folder and your Shaders folder. All under `Documents/Dolphin Emulator` on Windows.

I strongly recommend you download the latest release on our primary repository, which is based on a very up to date version of dolphin (the latest beta releases)

https://github.com/shiiion/dolphin/releases/tag/1.0.0

I also strongly recommend you see our guide on glitches and bugs, newer versions or different versions can have different issues, and depending on your hardware and the version they can behave in different ways. In other words an older version of Dolphin may lack a problem of a newer one, or it may be the opposite. This works vice versa. This guide aims to convey as many of the most effective fixes we know about.

https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs

> a recent commit 5 hours ago, and I am worried something may have been affected.

I apologise if I'm pointing out the obvious to you but I'm unsure of your experience as I don't know you. If you downloaded a release build, you will not have these latest commits. If you have cloned that commit and built it yourself, then you will.

> Are there any logging configs in place so I may troubleshoot? I noticed there were not any logs printed to the usual place for dolphin.

PrimeHack won't do anything to stop the game launching unless you've found a rare and ultra specific bug. You can verify this by disabling PrimeHack in the `Config` window. Remember savestates are buggy and shouldn't be used when trying to solve problems.

Dolphin itself has terrible logging. Even though it has so many logging options I've never seen them be useful or print any information on errors.



I recommend you join our Discord if you want faster responses, and there are more people who are knowledgeable and able to help you other than me, and shio.
https://discord.gg/tchQne2

**Comment by Jounreay** [comment]
My understanding is that a commit would be included in a new build if it's been rebuilt, and either you or someone else could do that and include it in the release on that webpage? Isn't that what tagging and version bumping is for? At my job we use nexus, so it is probably a convenience I just got used to. I haven't pulled from any repos that aren't work related, and it was on my mind as possible cause of the crash, not _the_ cause. 

As for the stable release of the game, i made certain to grab 5.0 _stable_. I am very aware dolphin is buggy, however, this specific release of prime hack doesn't work for metroid prime  even I disable just about everything; no hacks(including the hack this emulator is for), no additional shaders or visual options. I pulled up the 5.0 version of dolphin, and  side-by-side made the application configurations match, then did the same with the visual configs. No version of direct x worked, neither did open-GL,.

I will try what you told me about downloading a more recent release, but that was the first one I found, I wasn't aware there was a more recent version. I'll be sure to refresh the shader and  visual config cache to see if that makes a difference.

EDIT: I did download the latest version of primeHack, and unfortunately that was the version i was using last night.

EDIT: I also verified which version of dolphin I was using, and if I'm not mistaken, **this** is the latest; 5.0-12247.

Correct me if I'm wrong, but this seems specifically like an issue with PrimeHack?

**Comment by shiiion** [comment]
You can check the commit hash that a release is based on. Assuming you grabbed [this](https://github.com/shiiion/Ishiiruka/releases/tag/1.0.0) one, it does not contain any recent commits. Since you're using regular dolphin at the same time as this, my best guess is that your configs are clashing. Put prime hack in portable mode (place an empty file named portable.txt in the same directory as the executable).

**Comment by SirMangler** [comment]
> this specific release of prime hack doesn't work for metroid prime even I disable just about everything; no hacks(including the hack this emulator is for)

If you disabled PrimeHack and the problems are still prevalent, it means there's 99.9% chance PrimeHack isn't the problem.

> Correct me if I'm wrong, but this seems specifically like an issue with PrimeHack?

[Verify your dump's integrity](https://i.imgur.com/GowjRoV.png). You can do this by accessing the properties of the game inside dolphin, and going to the `Verify` tab. It's possible the newer versions can't cope with the errors in your dump (I have seen this before). PrimeHack is based on a beta release (I believe 1.0.0 is on the third latest one). Running PrimeHack with PrimeHack disabled is basically just running vanilla Dolphin. 

Like shio suggested you can run in portable mode, however doing what I suggested by removing those folders will achieve effectively the same thing, wiping and regenerating the relevant files.

> As for the stable release of the game, i made certain to grab 5.0 stable. I am very aware dolphin is buggy,

Dolphin 5.0 stable is an oxymoron. It is 4 years old and by modern standards it actually runs worse than the beta builds. Even the dolphin developers openly admit that 5.0 crashes *far* more than the betas and dev releases. The Graphics core has been nearly entirely rewritten since, comparing the settings to the latest versions is an unfair comparison internally. **I would never ever recommend using 5.0 "stable".**

> My understanding is that a commit would be included in a new build if it's been rebuilt, and either you or someone else could do that and include it in the release on that webpage

Releases are physically released by the developers. A release is simply the binary we have built and deemed ready for wide use. There is no automation involved. Like shio said, releases are based on commits. [The current release is based on this commit.
](https://github.com/shiiion/Ishiiruka/commit/62677096ecaa6e7d94de830c10199a91b660f887) This release has all commits *before* this release, all of the commits before the 4th of May, the day the release was published. It has none of the following or most recent ones.

> **this** is the latest; 5.0-12247.

The latest as of this comment is [5.0-12455](https://dolphin-emu.org/download/dev/55c931d6248c6dda5a8a9cbd332131255d62bc3f/). That version you mentioned is the latest beta, rather than the latest commit or "dev version" as it's known in the Dolphin community.

**Comment by SirMangler** [comment]
Closed for inactivity. See [our discord](https://discord.gg/tchQne2) or [the wiki](https://github.com/shiiion/dolphin/wiki/) for any further questions.
